version: 1.2
workflows:
 - subclass: WDL
   primaryDescriptorPath: /definitions/immuno.wdl
   name: immuno
- subclass: WDL
   primaryDescriptorPath: /definitions/detect_variants.wdl
   name: detect_variants
- subclass: WDL
   primaryDescriptorPath: /definitions/somatic_exome.wdl
   name: somatic_exome
   
